{{ $cert := genSelfSignedCert "mitigation-webhook-svc.mitigation-webhook-log4j.svc" nil (list "mitigation-webhook-svc.mitigation-webhook-log4j.svc" "mitigation-webhook-svc.mitigation-webhook-log4j.svc.cluster" "mitigation-webhook-svc.mitigation-webhook-log4j.svc.cluster.local") 3650 }}
apiVersion: v1
kind: Namespace
metadata:
  name: mitigation-webhook-log4j

---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: mitigation-webhook-log4j
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitigation-webhook
  namespace: mitigation-webhook-log4j
  labels:
    app: mitigation-webhook
    {{- include "k8s-webhook-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mitigation-webhook
      {{- include "k8s-webhook-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mitigation-webhook
        {{- include "k8s-webhook-chart.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: webhook-secret-vol
          secret:
            secretName: webhook-secret
      containers:
        - name: mitigation-webhook
          image: public.ecr.aws/v2k0k1b1/k8s/mitigation-webhook-log4j:v1.1.0
          ports:
            - containerPort: 8443
          args:
            - "--key=/certs/tls.key"
            - "--cert=/certs/tls.crt"
          volumeMounts:
            - name: webhook-secret-vol
              mountPath: "/certs"
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "512m"

---
apiVersion: v1
kind: Service
metadata:
  name: mitigation-webhook-svc
  namespace: mitigation-webhook-log4j
  labels:
    app: mitigation-webhook
    {{- include "k8s-webhook-chart.selectorLabels" . | nindent 4 }}
spec:
  selector:
    app: mitigation-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mitigation-webhook-config"
  labels:
    {{- include "k8s-webhook-chart.selectorLabels" . | nindent 8 }}
webhooks:
  - name: "mitigation-webhook-svc.mitigation-webhook-log4j.svc"
    namespaceSelector:
      matchExpressions:
        - key: "kubernetes.io/metadata.name"
          operator: NotIn
          values: ["kube-system", "kube-public", "mitigation-webhook-log4j"]
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "mitigation-webhook-log4j"
        name: "mitigation-webhook-svc"
        path: "/webhook"
        port: 443
      caBundle: {{ $cert.Cert | b64enc }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
